language: smalltalk
sudo: false

os:
  - linux

smalltalk:
  - Pharo-stable

env:
  global:
    - PILLAR_RELEASE=v7.7.3
    - TEXLIVE_RELEASE=2019
    - TEXLIVE_MIRROR=http://mirror.ctan.org/systems/texlive/tlnet
    - PATH="$HOME/texlive/bin/x86_64-linux:$HOME/pillar/build:$PATH"

install:
  - git clone --branch "$PILLAR_RELEASE" https://github.com/pillar-markup/pillar.git "$HOME/pillar"
  - ( cd $HOME/pillar; ./scripts/build.sh; )
  - $HOME/pillar/scripts/ci/install-texlive
  - ./_support/latex/ensure-deps.sh

script:
  - pillar build pdf

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - mv _result/pdf/index.pdf Commander-wip.pdf
  - bash upload.sh Commander-wip.pdf

branches:
  except:
    - /^(?i:continuous)$/
